services:
  - type: web
    name: arte-suave
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: NODE_ENV
        value: production
